source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

workspace 'CommonUX'
xcodeproj 'CommonUX.xcodeproj'

target 'CommonUX' do

pod 'MBProgressHUD', '~> 0.9.2'
pod 'IQKeyboardManagerSwift', '~> 4.0'
pod 'Parse', '~> 1.13'
pod 'ParseFacebookUtilsV4', '~> 1.11'
pod 'ParseTwitterUtils', '~> 1.10'
pod 'ParseUI', ‘~> 1.2.0’

end
