// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import ObjectiveC;
@import SystemConfiguration;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC8CommonUX18BaseViewController")
@interface BaseViewController : UIViewController
- (void)showProgress:(NSString * _Nonnull)title;
- (void)hideProgress;
- (void)showDialog:(NSString * _Nonnull)title message:(NSString * _Nonnull)message;
- (void)showErrorDialog:(NSString * _Nonnull)message;
- (void)showInfoDialog:(NSString * _Nonnull)message;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSError;

SWIFT_CLASS("_TtC8CommonUX25AccountFlowViewController")
@interface AccountFlowViewController : BaseViewController
+ (void (^ _Nullable)(NSError * _Nullable, BOOL))flowCompletionCallback;
+ (void)setFlowCompletionCallback:(void (^ _Nullable)(NSError * _Nullable, BOOL))value;
+ (UIViewController * _Nonnull)inflateVCNamed:(NSString * _Nonnull)name;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;
@class ChangePasswordViewController;

SWIFT_CLASS("_TtC8CommonUX28AccountManagerViewController")
@interface AccountManagerViewController : AccountFlowViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (IBAction)doClose;
+ (ChangePasswordViewController * _Nonnull)getChangePasswordViewControllerInstance;
+ (AccountManagerViewController * _Nonnull)gtAccountManagerViewControllerInstance;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC8CommonUX21AppInfoViewController")
@interface AppInfoViewController : BaseViewController
+ (void)launchVia:(UIViewController * _Nonnull)via logoImage:(UIImage * _Nullable)logoImage appTitle:(NSString * _Nullable)appTitle;
+ (AppInfoViewController * _Nonnull)getAppInfoViewControllerInstance;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC8CommonUX28ChangePasswordViewController")
@interface ChangePasswordViewController : AccountFlowViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSString * _Nullable)tableView:(UITableView * _Nonnull)tableView titleForHeaderInSection:(NSInteger)section;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX17ConnectionManager")
@interface ConnectionManager : NSObject
+ (NSString * _Nonnull)NOTIF_REACHABLE_BY_WIFI;
+ (NSString * _Nonnull)NOTIF_REACHABLE_BY_CELLULAR;
+ (NSString * _Nonnull)NOTIF_INTERNET_UNREACHABLE;
+ (NSString * _Nonnull)NOTIF_IOTC_UID_REACHABLE_BY_LAN;
+ (NSString * _Nonnull)NOTIF_IOTC_UID_REACHABLE_BY_INTERNET;
+ (NSString * _Nonnull)NOTIF_IOTC_UID_UNREACHABLE;
+ (NSString * _Nonnull)NOTIF_RDT_UID_REACHABLE_BY_LAN;
+ (NSString * _Nonnull)NOTIF_RDT_UID_REACHABLE_BY_INTERNET;
+ (NSString * _Nonnull)NOTIF_RDT_UID_UNREACHABLE;
+ (NSString * _Nonnull)NOTIF_HOME_AID_REACHABLE_BY_LAN;
+ (NSString * _Nonnull)NOTIF_HOME_AID_REACHABLE_BY_INTERNET;
+ (NSString * _Nonnull)NOTIF_HOME_AID_UNREACHABLE;
+ (ConnectionManager * _Nonnull)sharedInstance;
@property (nonatomic, readonly) BOOL isInternetReachableViaWifi;
@property (nonatomic, readonly) BOOL isInternetReachableViaCelluar;
@property (nonatomic, readonly) BOOL isInternetReachable;
- (BOOL)isUidReachableViaLAN:(NSString * _Nonnull)uid;
- (BOOL)isUidReachableViaInternet:(NSString * _Nonnull)uid;
@end


SWIFT_CLASS("_TtC8CommonUX23LoginFlowViewController")
@interface LoginFlowViewController : BaseViewController
+ (void (^ _Nullable)(NSError * _Nullable, BOOL, id _Nullable))flowCompletionCallback;
+ (void)setFlowCompletionCallback:(void (^ _Nullable)(NSError * _Nullable, BOOL, id _Nullable))value;
+ (UIViewController * _Nonnull)inflateVCNamed:(NSString * _Nonnull)name;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class PromptActivateAccountViewController;
@class LoginViewController;
@class UIView;
@class UITextField;
@class UILabel;
@class UITextView;
@class UIButton;

SWIFT_CLASS("_TtC8CommonUX27CreateAccountViewController")
@interface CreateAccountViewController : LoginFlowViewController
@property (nonatomic, weak) IBOutlet UIView * _Nullable termOfServiceHolderView;
@property (nonatomic, weak) IBOutlet UITextField * _Nullable firstNameTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Nullable lastNameTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Nullable emailTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Nullable passwordTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Nullable passwordConfirmTextField;
@property (nonatomic, weak) IBOutlet UILabel * _Nullable mainPromptLabel;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified termOfTextView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified termButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified createButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified alreadyHaveAccountButton;
@property (nonatomic, readonly, copy) NSString * _Nullable termOfServicePath;
- (void)viewDidLoad;
+ (PromptActivateAccountViewController * _Nonnull)getResetPasswordViewControllerInstance;
- (void)onCreateAccountError:(NSError * _Nonnull)error;
- (void)onCreateAccountSuccessWithEmail:(NSString * _Nonnull)email;
+ (LoginViewController * _Nonnull)getLoginViewControllerInstance;
+ (PromptActivateAccountViewController * _Nonnull)getPromptActivateAccountViewControllerInstance;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX15LANSearchResult")
@interface LANSearchResult : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable uid;
@property (nonatomic, readonly, copy) NSString * _Nullable ipv4;
@property (nonatomic, readonly, copy) NSString * _Nullable ipv6;
@property (nonatomic, readonly, copy) NSString * _Nullable name;
- (nonnull instancetype)initWithUid:(NSString * _Nullable)uid ipv4:(NSString * _Nullable)ipv4 ipv6:(NSString * _Nullable)ipv6 name:(NSString * _Nullable)name OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStoryboardSegue;

SWIFT_CLASS("_TtC8CommonUX23LANSearchViewController")
@interface LANSearchViewController : BaseViewController <UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UITableViewCell * _Nonnull)getViewForCellAtRow:(UITableView * _Nonnull)tableView row:(NSInteger)row withLANSearchResult:(LANSearchResult * _Nonnull)result;
- (void)cancel;
- (void)reload:(BOOL)withProgress completionHandler:(void (^ _Nullable)(void))completionHandler;
+ (void)launchForResultVia:(UIViewController * _Nonnull)via cb:(void (^ _Nullable)(NSError * _Nullable, LANSearchResult * _Nullable))cb;
+ (LANSearchViewController * _Nonnull)getLANSearchViewControllerInstance;
- (void)viewDidLoad;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@class UIImageView;

SWIFT_CLASS("_TtC8CommonUX25LoginSplashViewController")
@interface LoginSplashViewController : LoginFlowViewController
@property (nonatomic, strong) IBOutlet UIImageView * _Null_unspecified backgroundImageView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified loginButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified creatButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
+ (CreateAccountViewController * _Nonnull)getCreateAccountViewControllerInstance;
+ (LoginSplashViewController * _Nonnull)getLoginSplashViewControllerInstance;
+ (LoginViewController * _Nonnull)getLoginViewControllerInstance;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class ResetPasswordViewController;

SWIFT_CLASS("_TtC8CommonUX19LoginViewController")
@interface LoginViewController : LoginFlowViewController
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified createAccountButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified emailTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified passwordTextField;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified usernameIcon;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified passwordIcon;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified loginButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified forgotButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified loginViewBackground;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified whiteBackground;
- (void)viewDidLoad;
- (IBAction)doLogin;
- (void)onLoginError:(NSError * _Nonnull)error;
- (void)onLoginSuccessWithToken:(id _Nonnull)token;
+ (ResetPasswordViewController * _Nonnull)getResetPasswordViewControllerInstance;
+ (CreateAccountViewController * _Nonnull)getCreateAccountViewControllerInstance;
+ (LoginViewController * _Nonnull)getLoginViewControllerInstance;
+ (PromptActivateAccountViewController * _Nonnull)getPromptActivateAccountViewController;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX35PromptActivateAccountViewController")
@interface PromptActivateAccountViewController : LoginFlowViewController
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified whiteBackground;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified whiteBoardTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified whiteBoardContentLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified whiteBoardSecondContentLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified resendButton;
- (void)viewDidLoad;
- (void)onResendActivationEmailError:(NSError * _Nonnull)error;
- (void)onResendActivationEmailSuccess;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotificationCenter;

SWIFT_CLASS("_TtC8CommonUX12Reachability")
@interface Reachability : NSObject
@property (nonatomic, copy) void (^ _Nullable whenReachable)(Reachability * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable whenUnreachable)(Reachability * _Nonnull);
@property (nonatomic) BOOL reachableOnWWAN;
@property (nonatomic, strong) NSNotificationCenter * _Nonnull notificationCenter;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentReachabilityString;
- (nonnull instancetype)initWithReachabilityRef:(SCNetworkReachabilityRef _Nonnull)reachabilityRef OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithHostname:(NSString * _Nonnull)hostname error:(NSError * _Nullable * _Null_unspecified)error;
+ (Reachability * _Nullable)reachabilityForInternetConnectionAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
+ (Reachability * _Nullable)reachabilityForLocalWiFiAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (BOOL)startNotifierAndReturnError:(NSError * _Nullable * _Null_unspecified)error;
- (void)stopNotifier;
- (BOOL)isReachable;
- (BOOL)isReachableViaWWAN;
- (BOOL)isReachableViaWiFi;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC8CommonUX27ResetPasswordViewController")
@interface ResetPasswordViewController : LoginFlowViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified whiteBackground;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified whiteBoardTitle;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified whiteBoardContentLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified inputBackgroundView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified emailIcon;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified emailTextField;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified resetButton;
- (void)viewDidLoad;
- (void)onResetPasswordError:(NSError * _Nonnull)error;
- (void)gotoSplashViewController;
- (void)onResetPasswordSuccess;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class SACellModel;
@class UICollectionView;

SWIFT_CLASS("_TtC8CommonUX6SACell")
@interface SACell : UICollectionViewCell
@property (nonatomic, readonly, weak) SACellModel * _Nullable _cellmodel;
@property (nonatomic) BOOL shouldSelect;
@property (nonatomic) BOOL shouldDeselect;
@property (nonatomic) BOOL shouldHighlight;
- (void)configure;
- (void)configureForSizeCalculating:(SACellModel * _Nonnull)cellmodel;
- (void)willDisplay:(UICollectionView * _Nonnull)collectionView;
- (void)didEndDisplaying:(UICollectionView * _Nonnull)collectionView;
- (void)didHighlight:(UICollectionView * _Nonnull)collectionView;
- (void)didUnhighlight:(UICollectionView * _Nonnull)collectionView;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX11SACellModel")
@interface SACellModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull reuseIdentifier;
@property (nonatomic, readonly, strong) NSIndexPath * _Nonnull indexPath;
@property (nonatomic, copy) void (^ _Nullable selectionHandler)(SACell * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable deselectHandler)(SACell * _Nonnull);
@property (nonatomic) CGFloat width;
@property (nonatomic) CGSize size;
- (void)enableDynamicHeight:(CGFloat)width;
- (void)disableDynamicHeight;
- (void)setPreCalculatedSize:(CGSize)size;
- (void)deselect:(BOOL)animated;
- (void)bump;
@end


@interface SACellModel (SWIFT_EXTENSION(CommonUX))
@end


SWIFT_CLASS("_TtC8CommonUX12SAFlowLayout")
@interface SAFlowLayout : UICollectionViewFlowLayout
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView sizeForCellModel:(SACellModel * _Nonnull)cellmodel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX29SAFlowLayoutSupplementaryView")
@interface SAFlowLayoutSupplementaryView : UICollectionReusableView
- (void)configure;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX8SALayout")
@interface SALayout : UICollectionViewLayout
- (SACellModel * _Nullable)getCellModel:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<SACellModel *> * _Nonnull)getCellModels:(NSInteger)section;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SapporoDelegate;

SWIFT_CLASS("_TtC8CommonUX7Sapporo")
@interface Sapporo : NSObject
@property (nonatomic, readonly, strong) UICollectionView * _Nonnull collectionView;
@property (nonatomic, weak) id <SapporoDelegate> _Nullable delegate;
@property (nonatomic, copy) void (^ _Nullable loadmoreHandler)(void);
@property (nonatomic) BOOL loadmoreEnabled;
@property (nonatomic) CGFloat loadmoreDistanceThreshold;
@property (nonatomic, copy) void (^ _Nullable willBumpHandler)(NSInteger);
@property (nonatomic, readonly) NSInteger sectionsCount;
- (SACellModel * _Nullable)objectForKeyedSubscript:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithCollectionView:(UICollectionView * _Nonnull)collectionView OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)bump;
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX))
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX))
- (void)setLayout:(UICollectionViewLayout * _Nonnull)layout;
- (void)setLayout:(UICollectionViewLayout * _Nonnull)layout animated:(BOOL)animated;
- (void)setLayout:(UICollectionViewLayout * _Nonnull)layout animated:(BOOL)animated completion:(void (^ _Nonnull)(BOOL))completion;
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX))
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX)) <UICollectionViewDataSource>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX))
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UIEdgeInsets)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout insetForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section;
@end

@class UIScrollView;

@interface Sapporo (SWIFT_EXTENSION(CommonUX))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Null_unspecified)targetContentOffset;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScrollToTop:(UIScrollView * _Nonnull)scrollView;
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX))
@property (nonatomic, readonly) BOOL isEmpty;
@property (nonatomic, readonly) BOOL isNotEmpty;
@property (nonatomic, readonly) BOOL isFlowLayout;
@property (nonatomic, readonly) UICollectionViewScrollDirection direction;
- (SACell * _Nullable)cellAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UICollectionViewTransitionLayout;

@interface Sapporo (SWIFT_EXTENSION(CommonUX)) <UICollectionViewDelegate, UIScrollViewDelegate>
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didDeselectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldHighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didHighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didUnhighlightItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplaySupplementaryView:(UICollectionReusableView * _Nonnull)view forElementKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingSupplementaryView:(UICollectionReusableView * _Nonnull)view forElementOfKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView canPerformAction:(SEL _Null_unspecified)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView performAction:(SEL _Null_unspecified)action forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath withSender:(id _Nullable)sender;
- (BOOL)collectionView:(UICollectionView * _Nonnull)collectionView shouldShowMenuForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionViewTransitionLayout * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView transitionLayoutForOldLayout:(UICollectionViewLayout * _Nonnull)fromLayout newLayout:(UICollectionViewLayout * _Nonnull)toLayout;
@end


@interface Sapporo (SWIFT_EXTENSION(CommonUX))
- (nonnull instancetype)reset;
- (nonnull instancetype)remove:(NSInteger)index;
- (nonnull instancetype)removeWithIndexes:(NSArray<NSNumber *> * _Nonnull)indexes;
- (nonnull instancetype)removeLast;
- (nonnull instancetype)removeAll;
- (nonnull instancetype)move:(NSInteger)from to:(NSInteger)to;
@end


SWIFT_PROTOCOL("_TtP8CommonUX15SapporoDelegate_")
@protocol SapporoDelegate
@optional
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScrollToTop:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Null_unspecified)targetContentOffset;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (UICollectionViewTransitionLayout * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView transitionLayoutForOldLayout:(UICollectionViewLayout * _Nonnull)fromLayout newLayout:(UICollectionViewLayout * _Nonnull)toLayout;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplaySupplementaryView:(UICollectionReusableView * _Nonnull)view forElementKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didEndDisplayingSupplementaryView:(UICollectionReusableView * _Nonnull)view forElementOfKind:(NSString * _Nonnull)elementKind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class TGService;

SWIFT_CLASS("_TtC8CommonUX11TGAccessory")
@interface TGAccessory : NSObject
- (NSString * _Nullable)getUid;
- (void)setUid:(NSString * _Nonnull)mstrUid;
- (NSInteger)getAID;
- (NSInteger)getIconType;
- (NSString * _Nullable)getName;
- (NSArray<TGService *> * _Nonnull)getTGServices;
- (nonnull instancetype)initWithAID:(NSString * _Nonnull)strAID name:(NSString * _Nonnull)strAName iconType:(NSInteger)nIconType roomName:(NSString * _Nonnull)strRoomName services:(NSArray<TGService *> * _Nonnull)tgServices connection:(NSInteger)connection bridged:(BOOL)bridged OBJC_DESIGNATED_INITIALIZER;
- (void)connect:(NSInteger)time_in_ms;
@end


SWIFT_CLASS("_TtC8CommonUX18TGAccessoryBrowser")
@interface TGAccessoryBrowser : NSObject
- (NSArray<TGAccessory *> * _Nonnull)getDiscoveredAccessories;
@end


SWIFT_CLASS("_TtC8CommonUX8TGAction")
@interface TGAction : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX11TGActionSet")
@interface TGActionSet : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX19TGConnectionManager")
@interface TGConnectionManager : NSObject
- (void)connet:(NSInteger)time_in_ms;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX9TGElement")
@interface TGElement : NSObject
- (NSString * _Nullable)getElementType;
- (void)bootstrap;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX17TGElementMetaData")
@interface TGElementMetaData : NSObject
- (nonnull instancetype)initWithMinimumValue:(NSInteger)minimumValue maximumValue:(NSInteger)maximumValue stepValue:(NSInteger)stepValue format:(NSString * _Nonnull)format units:(NSString * _Nonnull)units OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX14TGElementValue")
@interface TGElementValue : NSObject
@end


SWIFT_CLASS("_TtC8CommonUX7TGError")
@interface TGError : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TGServiceGroup;

SWIFT_CLASS("_TtC8CommonUX6TGHome")
@interface TGHome : NSObject
- (NSArray<TGServiceGroup *> * _Nonnull)getServiceGroups;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX13TGHomeManager")
@interface TGHomeManager : NSObject
- (TGHome * _Nullable)getPrimaryHome;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX6TGRoom")
@interface TGRoom : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX9TGService")
@interface TGService : NSObject
- (NSString * _Nullable)getstrSName;
- (NSArray<TGElement *> * _Nonnull)getElementList;
- (nonnull instancetype)initWithListElement:(NSArray<TGElement *> * _Nonnull)listElement OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX14TGServiceGroup")
@interface TGServiceGroup : NSObject
- (NSArray<TGService *> * _Nonnull)getServices;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX9TGTrigger")
@interface TGTrigger : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX6TGUser")
@interface TGUser : NSObject
- (NSString * _Nullable)getName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CommonUX6TGZone")
@interface TGZone : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIAlertController (SWIFT_EXTENSION(CommonUX))
+ (void)initialize;
@end


@interface UICollectionReusableView (SWIFT_EXTENSION(CommonUX))
+ (NSString * _Nonnull)nibName;
+ (NSString * _Nonnull)reuseIdentifier;
@end


@interface UICollectionView (SWIFT_EXTENSION(CommonUX))
@end

@class NSURL;

SWIFT_CLASS("_TtC8CommonUX24WebBrowserViewController")
@interface WebBrowserViewController : BaseViewController
@property (nonatomic, strong) NSURL * _Nullable url;
@property (nonatomic) BOOL presentedModally;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
